version: '3.8'

services:
  # Serviço Laravel (backend)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    # Sobrescreve o comando padrão
    command: >
      sh -c "
        # espera o MySQL subir (simples polling)
        until nc -z mysql 3306; do
          echo 'Aguardando banco de dados…'
          sleep 2
        done &&
        cd /var/www &&
        composer install &&
        php artisan optimize &&
        php artisan route:clear &&
        php artisan migrate --force &&
        #php artisan db:seed --force &&
        php artisan test --stop-on-failure &&
        php-fpm
      "

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  # Serviço VueJS (frontend)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: vuejs-app
    container_name: vuejs-app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  db_data: